import pint
from django.core.exceptions import ValidationError

def validat_unit_of_measure(value):
    
    print('11111111111111111111111')
    # # try:
    # #     single_unit = urag[value]
    # #     print(single_unit,'22222222222222222222222222222')
    # # except UndefinedUnitError as e :
    # #     raise ValidationError(f'{value} is not avalid unit of mesure')
    # # except:
    # #     raise ValidationError(f'{value} is not avalid unit of mesure')